### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hpk22** [shashankbafna/cowin-vaccination-book-slot#1]
Can otp be also automated by any means. It would make this app just great!?
Also can we able to download appointment slip from telegram itself?

**Comment by shashankbafna** [comment]
Yes, OTP surely can be automated in Android, however, we personally do not have phones to test or build a solution. I have tried simulators, however, they are of no use in case of receiving an SMS.

Secondly, yes I can add download appointment slip once slot is booked, that is quite easy & doable. We purposely did not do this because accessing COWIN portal is not slow or hard, however, problem statement was booking the slot, where we found this solution. I will try looking at this to enhance & update the code.

Thank you for your valuable suggestion.
